FROM ubuntu:14.04

RUN \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y build-essential && \
    apt-get install -y python3 && \
    apt-get install -y python-mysqldb && \
    apt-get install -y mysql-server && \
    apt-get install -y git man vim curl wget